# Generated by Django 4.2.7 on 2023-12-04 02:23

import django.contrib.auth.hashers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.hashers.make_password], verbose_name='password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
